pipeline
{
 agent any

 parameters {
  choice choices: ['chrome', 'firefox'], description: 'Select The Browser', name: 'BROWSER'
}


 stages 
 {
     stage('Start grid With 2 chrome or firefox')
     {
        steps 
        {
            sh "docker-compose -f grid.yaml up --scale ${params.BROWSER}=2 -d"

        }

     }

     stage('Start Testsuites')
     {
        steps 
        {
            sh "docker-compose -f 05-jenkins-ci-cd/10-runner-approach-1/test-suite.yaml up"
        }

     }
     
     stage('Check working directory')
     {
        steps 
        {
            sh 'pwd'
            sh 'ls -l 05-jenkins-ci-cd/10-runner-approach-1/output/flight-reservation/'
            sh 'ls -l 05-jenkins-ci-cd/10-runner-approach-1/output/vendor-portal/'
            
        }

     }
     

     }
     post 
     {
        always
        {
            
            
            sh "docker-compose -f 05-jenkins-ci-cd/10-runner-approach-1/grid.yaml down"
            sh "docker-compose -f 05-jenkins-ci-cd/10-runner-approach-1/test-suite.yaml down"
            archiveArtifacts artifacts: '05-jenkins-ci-cd/10-runner-approach-1/output/flight-reservation/emailable-report.html', followSymlinks: false
            archiveArtifacts artifacts: '05-jenkins-ci-cd/10-runner-approach-1/output/vendor-portal/emailable-report.html', followSymlinks: false
            
            
        }
     }

}