pipeline
{
 agent any

 stages 
 {
     stage('Start grid')
     {
        steps 
        {
            sh "docker-compose -f grid.yaml up -d"
        }

     }

     stage('Start Testsuites')
     {
        steps 
        {
            sh "docker-compose -f test-suite.yaml up"
        }

     }

     }
     post 
     {
        always
        {
            sh "docker-compose -f grid.yaml down"
            sh "docker-compose -f test-suite.yaml down"
        }
     }

}