pipeline
{
 agent any

 stages 
 {
     stage('Start grid')
     {
        steps 
        {
            sh "docker-compose -f 05-jenkins-ci-cd/10-runner-approach-1/grid.yaml up -d"

        }

     }

     stage('Start Testsuites')
     {
        steps 
        {
            sh "docker-compose -f 05-jenkins-ci-cd/10-runner-approach-1/test-suite.yaml up"
        }

     }

     }
     post 
     {
        always
        {
            sh "docker-compose -f 05-jenkins-ci-cd/10-runner-approach-1/grid.yaml down"
            sh "docker-compose -f 05-jenkins-ci-cd/10-runner-approach-1/test-suite.yaml down"
            archiveArtifacts artifacts: 'output/flight-reservation/emailable-report.html', followSymlinks: false
            archiveArtifacts artifacts: 'output/vendor-portal/emailable-report.html', followSymlinks: false
        }
     }

}